config/routes.rb
Rails.application.routes.draw do
  resources :projects
  root "home#index"
  get 'helium/:action', controller: 'helium'
  get "stimulus/carousel"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  enum :stage, {
      development: "development",
      staging: "staging",
      preprod: "preprod",
      production: "production"
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/helium_controller.rb
class HeliumController < ApplicationController
  def index
  end

  def basics
  end

  def ajax
  end

  def carousel
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.turbo_stream
        format.html { redirect_to @project, notice: "Project was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_path, notice: "Project was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.expect(project: [ :name, :active, :stage ])
    end
end

app/controllers/stimulus_controller.rb
class StimulusController < ApplicationController
  def carousel
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def he(name, record)
    model = record.model_name.singular
    id    = record.id
    "#{name}_#{model}_#{id}"
  end
end

app/helpers/helium_helper.rb
module HeliumHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/stimulus_helper.rb
module StimulusHelper
end

app/views/helium/ajax.html.erb
<div @data="{
    templates: {
      post: data => `
        <section class='post'>
          <h1>${data?.title}</h1>
          <p>${data?.body}</p>
        </section>`
    }
  }"
</div>

<div class="page">
  <h1>🎈 Helium Ajax Examples</h1>

  <div class="examples">

    <!-- Ajax Example -->
    <section class="card">
      <h2>HTML Response</h2>
      <p id="table">
        Replace this paragraph with an HTML table by clicking on the button below.
      </p>
      <button
        @get.once="https://html-mock.fly.dev/tag/table"
        @target="#table:replace"
        @loading="<img src='https://media1.tenor.com/m/tEBoZu1ISJ8AAAAC/spinning-loading.gif' width=120 alt='Loading...'>"
      >
        Get HTML table
      </button>
    </section>

    <!-- Requests Example -->
    <section class="card">
      <h2>Request Methods</h2>
      <p>
        Make a PUT and DELETE request using the buttons below. The delete request requires you to hold down the shift key while clicking.
      </p>
      <div class="button-group">
        <button
          @put="https://html-mock.fly.dev/tag/paragraph"
          @loading="account loading..."
          @params="{cash: 2}"
          @target="put_response"
        >
          Put Money In Your Account
        </button>

        <button
          @delete.shift="https://html-mock.fly.dev/tag/paragraph"
          @params="{account: 1}"
          @loading="account loading..."
          @target="delete_response"
        >
          Delete Your Account
        </button>
      </div>

      <div @html="put_response" class="response blue">Put response</div>
      <div @html="delete_response" class="response red">Delete response</div>
    </section>

    <!-- Posts Example -->
    <section @ref="posts" class="card lg:col-span-2">
        <h2>Posts (JSON response)</h2>
         <p>
           Add new posts to the list below. Create your own with the form below.
           Try clicking the GET POST button repeatedly — it’s debounced to avoid multiple adds.
         </p>

         <form @ref="form" class="form">
           <label>
             <span>Title:</span>
             <input type="hidden" name="userId" value="5">
             <input name="title">
           </label>

           <label>
             <span>Body:</span>
             <textarea name="body"></textarea>
           </label>

           <button
             @post.prevent="https://dummyjson.com/posts/add?delay=5000"
             @params="new FormData($form)"
             @target="$posts:append"
             @template="templates.post"
             @loading = "templates.post({title: $form.title.value, body: $form.body.value})"
           >
             Create New Post
           </button>
         </form>

         <div class="button-group">
           <button
             @get.debounce:700="https://dummyjson.com/posts/1?delay=5000"
             @target="$posts:append"
             @loading="<p>Post is <b>loading</b></p>"
             @template="templates.post"
             @loading = "loading post ..."
           >
             Get Post
           </button>
         </div>
       </section>


  </div>
</div>

app/views/helium/basics.html.erb
<div class="page" @effect:*="console.log('something changed ...')">
  <h1>🎈 Helium Examples</h1>

  <div class="examples">

    <!-- Counter -->
    <div class="card">
      <h2>Counter</h2>
      <button @click="count++">Clicked <b @text="count">0</b> times</button>
    </div>

    <!-- Dynamic Classes -->
    <div
      @data="{ active: false }"
      :class="{'bg-red-400': active}"
      class="card"
    >
      <h2>Dynamic Classes</h2>
      <button @click="active = !active">Toggle</button>
    </div>

    <!-- Two-way Binding with Calculate -->
    <div class="card">
      <h2>2-Way Bindings</h2>
      <input
        @bind="firstname"
        placeholder="First name"
      >
      <input
        @bind="lastname"
        placeholder="Last name"
      >
      <span
        @calculate:fullName="firstname && lastname ? firstname + ' ' + lastname : firstname || lastname || ''"
      ></span>
      <p>Hello <b @text="fullname"></b></p>
      <button @click="firstname = '', lastname = ''">Clear</button>
    </div>

    <!-- Visibility Toggle -->
    <div @data="{ show: false }" class="card">
      <h2>Visibility Toggle</h2>
      <button @click="show = !show">Toggle</button>
      <p @visible="show">Now you see me!</p>
    </div>

  </div>
</div>

app/views/helium/carousel.html.erb
<% ids = %w(25 29 35 56 77 82 89 90 102 107) %>
<div data-he="{carousel_open: false, index: 0}">
    <!-- Image Grid -->
    <div class="flex gap-6 w-full justify-stretch p-4">
        <div class="grid grid-cols-5 gap-3">
            <% ids.each_with_index do |pic, index| %>
                <div class="aspect-square flex items-center justify-center rounded-lg shadow-md cursor-pointer transition transform hover:scale-110 hover:shadow-lg bg-gradient-to-br from-gray-50 to-gray-100
 hover:from-blue-50 hover:to-blue-100 " data-he-click="carousel_open = true, index=<%= index %>" >
                    <%= image_tag "https://picsum.photos/id/#{pic}/300/300",
                                  class: "w-full h-full object-cover rounded-lg pointer-events-none" %>
                </div>
            <% end %>
        </div>
    </div>
    <!-- Modal -->
    <div data-he-visible="carousel_open" class="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center transition-opacity duration-300 ">
     <div class="relative w-full max-w-4xl aspect-[16/9] bg-gray-900 rounded-xl overflow-hidden shadow-2xl ring-1 ring-white/10">
         <div class="overflow-hidden h-full rounded-lg relative">
             <% ids.each_with_index do |pic, index| %>
                 <%= image_tag "https://picsum.photos/id/#{pic}/1200/800",
                    class: "absolute inset-0 w-full h-full object-cover transition-opacity duration-300",
                    data: {
                        he_visible: "index == #{index}"
                    },
                    "aria-label": "Slide #{index + 1}" %>
            <% end %>
         </div>
        <!-- Nav Buttons -->
        <button type="button"
            data-he-click="index = (index + <%= ids.size %> - 1) % <%= ids.size %>"
            data-he-keydown.document.arrowleft="index = (index + <%= ids.size %> - 1) % <%= ids.size %>"
            class=" absolute left-3 top-1/2 -translate-y-1/2 bg-white/20 hover:bg-white/30 text-white text-3xl font-bold px-4 py-2 rounded-full shadow-md backdrop-blur transition transform hover:scale-105 " >
                &lt;
        </button>
        <button type="button"
            data-he-keydown.document.arrowright="index = (index + 1) % <%= ids.size %>"
            data-he-click="index = (index + 1) % <%= ids.size %>"
            class=" absolute right-3 top-1/2 -translate-y-1/2 bg-white/20 hover:bg-white/30 text-white text-3xl font-bold px-4 py-2 rounded-full shadow-md backdrop-blur transition transform hover:scale-105" >
                &gt;
        </button>
        <!-- Close Button -->
        <button type="button"
            data-he-keypress.document.esc="carousel_open = false"
            data-he-click="carousel_open = false"
            class=" absolute top-3 right-4 text-3xl text-white/80 hover:text-white transition bg-white/10 hover:bg-white/20 rounded-full w-10 h-10 flex items-center justify-center
        shadow-md backdrop-blur " >
            &times;
        </button>
     </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Helium Demo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Helium Demo">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="min-h-screen bg-gradient-to-br from-pink-100 via-white to-blue-100 flex flex-col items-center p-10">
        <h1 class="text-6xl font-bold mb-10 bg-gradient-to-r from-sky-200 via-pink-300 to-yellow-100 inline-block text-transparent bg-clip-text"><%= link_to "Beyond Stimulus", root_path %></h1>

        <%= yield %>
        <ul class="flex space-x-4 border-b border-slate-200">
          <li>
            <%= link_to "Helium Basic Examples",
                  "/helium/basics",
                  class: "px-4 py-2 inline-block rounded-t-lg bg-slate-100 text-slate-700 hover:bg-slate-200 hover:text-slate-900 transition" %>
          </li>

          <li>
            <%= link_to "Stimulus Carousel",
                  "/stimulus/carousel",
                  class: "px-4 py-2 inline-block rounded-t-lg bg-slate-100 text-slate-700 hover:bg-slate-200 hover:text-slate-900 transition" %>
          </li>

          <li>
            <%= link_to "Helium Carousel",
                  "/helium/carousel",
                  class: "px-4 py-2 inline-block rounded-t-lg bg-slate-100 text-slate-700 hover:bg-slate-200 hover:text-slate-900 transition" %>
          </li>

          <li>
            <%= link_to "Helium Ajax Examples",
                  "/helium/ajax",
                  class: "px-4 py-2 inline-block rounded-t-lg bg-slate-100 text-slate-700 hover:bg-slate-200 hover:text-slate-900 transition" %>
          </li>

          <li>
            <%= link_to "Rails Projects",
                  "/projects",
                  class: "px-4 py-2 inline-block rounded-t-lg bg-slate-100 text-slate-700 hover:bg-slate-200 hover:text-slate-900 transition" %>
          </li>
        </ul>
    </main>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, class: "contents") do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul class="list-disc ml-6">
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": project.errors[:name].none?, "border-red-400 focus:outline-red-600": project.errors[:name].any?}] %>
  </div>

  <div class="my-5 flex items-center gap-2">
    <%= form.label :active %>
    <%= form.checkbox :active, class: ["block shadow-sm rounded-md border order-first h-5 w-5", {"border-gray-400 focus:outline-blue-600": project.errors[:active].none?, "border-red-400 focus:outline-red-600": project.errors[:active].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :stage %>
    <%= form.number_field :stage, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": project.errors[:stage].none?, "border-red-400 focus:outline-red-600": project.errors[:stage].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= project.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Active:</strong>
    <%= project.active? ? "Yes" : "No" %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Stage:</strong>
    <%= project.stage %>
  </div>
</div>

app/views/projects/edit.html.erb
<% content_for :title, "Editing project" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing project</h1>

  <%= render "form", project: @project %>

  <%= link_to "Show this project", @project, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to projects", projects_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/projects/index.html.erb
<% content_for :title, "Projects" %>

<div class="w-full space-y-8"
     data-he="{
            timestamp: 0,
        }"
     data-he-init="setInterval(() => timestamp = Date.now(),1000)"
     data-he-import="time_ago_in_words"
>
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 text-green-700 font-medium rounded-md inline-block shadow-sm" id="notice">
      <%= notice %>
    </p>
  <% end %>

  <!-- Header -->
  <div class="flex justify-between items-center">
    <h1 class="font-extrabold text-5xl tracking-tight text-slate-900 drop-shadow-sm">
      Projects
    </h1>

    <%= link_to "New project",
      new_project_path,
      class: "rounded-xl px-5 py-3 bg-blue-600 hover:bg-blue-500 text-white font-semibold shadow-lg shadow-blue-200 transition-all" %>
  </div>

  <!-- Cards Grid -->
  <div id="projects" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">

    <% if @projects.any? %>
      <% @projects.each do |project| %>

        <div data-he-attr:class="{'bg-blue-100': <%= he(:active,project) %>}" class="border border-slate-200 rounded-2xl shadow-md p-6 hover:shadow-xl transition-all">

          <!-- Project Name -->
          <h2 class="text-4xl font-bold text-blue-800 mb-6 border-b border-slate-200 pb-3">
            <%= project.name %>
          </h2>

          <%= form_with model: project, url: "#", method: :get, class: "space-y-6" do |f| %>

            <!-- Active Checkbox -->
            <div class="flex items-center space-x-3">
              <%= f.check_box :active,
                    checked: project.active,
                    data: {
                        he_bind: he(:active,project),
                        he_patch: project_url(project),
                    },
                    class: "h-5 w-5 rounded border-slate-400 text-blue-600 focus:ring-blue-500 cursor-pointer" %>

              <label class="text-slate-800 font-medium">
                Active
              </label>
            </div>

            <!-- Stage Select -->
            <div>
              <%= f.select :stage,
                    Project.stages.keys.map { |s| [s.humanize, s] },
                    { selected: project.stage },
                    data: {
                        he_bind: he(:stage,project),
                        he_patch: project_url(project),
                    },
                    class: "w-full border border-slate-300 rounded-lg px-3 py-2 bg-white text-slate-800 shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
            </div>

            <!-- Radio Group -->
            <div>

              <div class="space-y-2">

                <% Project.stages.keys.each do |stage| %>
                  <label class="flex items-center space-x-2 cursor-pointer text-gray-700">
                      <%= f.radio_button :stage, stage,
                            checked: project.stage == stage,
                            data: { he_bind: he(:stage,project),
                                    he_patch: project_url(project),
                            },
                            class: "h-5 w-5 border-gray-300 text-blue-600 focus:ring-blue-500"
                      %>

                    <span class="text-slate-800 font-medium">
                      <%= stage.titleize %>
                    </span>
                  </label>
                <% end %>

              </div>
              <p>This project is currently <b data-he-text="<%= he(:active,project) %> ? 'active' : 'inactive'"></b></p>
            </div>

          <% end %>
        </div>

      <% end %>

    <% else %>
      <p class="text-center text-slate-500 py-10 col-span-3">No projects found.</p>
    <% end %>

  </div>
</div>
<div id="messages" class="mt-4 w-full"></div>

app/views/projects/new.html.erb
<% content_for :title, "New project" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New project</h1>

  <%= render "form", project: @project %>

  <%= link_to "Back to projects", projects_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/projects/show.html.erb
<% content_for :title, "Showing project" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing project</h1>

  <%= render @project %>

  <%= link_to "Edit this project", edit_project_path(@project), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to projects", projects_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this project", @project, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>

app/views/projects/update.turbo_stream.erb
<%= turbo_stream.append "messages" do %>
  <div class="w-3/4 p-3 mx-auto mb-2 rounded bg-blue-50 text-blue-800 border border-blue-200 shadow-sm">
      <b data-he-text="time_ago_in_words(Math.floor((timestamp/1000 - <%= Time.now.to_i %>)/60))"></b>:
      <%= @project.name %> Project updated!
      It is currently <b data-he-text="<%= he(:active,@project) %> ? 'active' : 'inactive'"></b>
  </div>
<% end %>

app/views/stimulus/carousel.html.erb
<% ids = %w(25 29 35 56 77 82 89 90 102 107) %>


<div
data-controller="carousel">

    <!-- Image Grid -->
    <div class="flex gap-6 w-full justify-stretch p-4">
        <div class="grid grid-cols-5 gap-3">
            <% ids.each_with_index do |pic, index| %>
                <div class=" aspect-square flex items-center justify-center rounded-lg shadow-md cursor-pointer transition transform hover:scale-110 hover:shadow-lg bg-gradient-to-br from-gray-50 to-gray-100
 hover:from-blue-50 hover:to-blue-100 "
                    data-index="<%=index%>"
                    data-action="click->carousel#openIndex" >
                    <%= image_tag "https://picsum.photos/id/#{pic}/300/300",
                                  class: "w-full h-full object-cover rounded-lg pointer-events-none" %>
                </div>
            <% end %>
        </div>
    </div>

    <!-- Modal -->
    <div data-carousel-target="modal" class="hidden fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center transition-opacity duration-300 ">
     <div class="relative w-full max-w-4xl aspect-[16/9] bg-gray-900 rounded-xl overflow-hidden shadow-2xl ring-1 ring-white/10">
         <div class="overflow-hidden h-full rounded-lg relative">
             <% ids.each_with_index do |pic, index| %>
                 <%= image_tag "https://picsum.photos/id/#{pic}/1200/800",
                    class: "absolute inset-0 w-full h-full object-cover transition-opacity duration-300",
                    data: {
                        carousel_target: "slide"
                    },
                    "aria-label": "Slide #{index + 1}" %>
            <% end %>
         </div>
        <!-- Nav Buttons -->
        <button type="button"
            data-action="click->carousel#previous"
            class=" absolute left-3 top-1/2 -translate-y-1/2 bg-white/20 hover:bg-white/30 text-white text-3xl font-bold px-4 py-2 rounded-full shadow-md backdrop-blur transition transform hover:scale-105 " >
                &lt;
        </button>
        <button type="button"
            data-action="click->carousel#next"
            class=" absolute right-3 top-1/2 -translate-y-1/2 bg-white/20 hover:bg-white/30 text-white text-3xl font-bold px-4 py-2 rounded-full shadow-md backdrop-blur transition transform hover:scale-105" >
                &gt;
        </button>
        <!-- Close Button -->
        <button type="button"
            data-action="click->carousel#close"
            class=" absolute top-3 right-4 text-3xl text-white/80 hover:text-white transition bg-white/10 hover:bg-white/20 rounded-full w-10 h-10 flex items-center justify-center
        shadow-md backdrop-blur " >
            &times;
        </button>
     </div>
 </div>
</div>